apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanicclass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: titanicclassifier
  template:
    metadata:
      labels:
        app: titanicclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/MLE-test/titanicwebapp:v1
        ports:
        - containerPort: 8501